apiVersion: karpenter.sh/v1
kind: Provisioner
metadata:
  name: on-demand
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.micro", "t3.small"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "kubernetes.io/os"
      operator: In
      values: ["linux"]

  labels:
    node-type: on-demand
    workload: nginx

  taints:
    - key: "workload"
      value: "nginx"
      effect: "NoSchedule"

  limits:
    resources:
      cpu: 500

  providerRef:
    name: aws-on-demand

  consolidation:
    enabled: true

  ttlSecondsAfterEmpty: 60

---
apiVersion: karpenter.k8s.aws/v1
kind: AWSNodeTemplate
metadata:
  name: aws-on-demand
spec:
  amiFamily: Bottlerocket
  subnetSelector:
    karpenter.sh/discovery: eks-karpenter-demo
  securityGroupSelector:
    karpenter.sh/discovery: eks-karpenter-demo
  instanceProfile: karpenter-controller-eks-karpenter-demo
  tags:
    Name: karpenter-on-demand-node
    karpenter.sh/discovery: eks-karpenter-demo
